
DROP TABLE IF EXISTS TRANSACTION;
DROP TABLE IF EXISTS ACCOUNT;
DROP TABLE IF EXISTS GROUP_TRANSACTION;

--
-- App tables
--

CREATE TABLE GROUP_TRANSACTION (
	ID SERIAL PRIMARY KEY
);

CREATE TABLE ACCOUNT (
	ID SERIAL PRIMARY KEY,
	NAME VARCHAR(200),
	BALANCE DECIMAL(12,2),
	STARTED DECIMAL(12,2)
);

CREATE TABLE TRANSACTION (
	ID SERIAL PRIMARY KEY,
	ACCOUNT_ID BIGINT,
	GROUP_TRANSACTION_ID BIGINT,
	STATUS VARCHAR(20),
	ACTION VARCHAR(20),
	VALUE DECIMAL(12,2),
	CREATED_AT TIMESTAMP,
	UPDATED_AT TIMESTAMP,
	SCHEDULED_AT TIMESTAMP,
	FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ID),
	FOREIGN KEY (GROUP_TRANSACTION_ID) REFERENCES GROUP_TRANSACTION(ID)
);
